### ISSUE TITLE
Missing dependencies required to use `IpynbFormat` instances

### ISSUE THREAD

**Issue by philipobrien** [airbnb/knowledge-repo#159]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Following the install steps does not satisfy all dependencies

```
$ git clone https://github.com/airbnb/knowledge-repo.git
$ cd knowledge-repo
$ pip install --upgrade knowledge-repo
$ knowledge_repo --repo ./example_repo init
$ knowledge_repo --repo ./example_repo create ipynb example_post.ipynb
$ knowledge_repo --repo ./example_repo add example_post.ipynb -p project/example_ipynb
```

at which point I get

```
Traceback (most recent call last):
  File "/usr/local/bin/knowledge_repo", line 249, in <module>
    kp = knowledge_repo.KnowledgePost.from_file(args.filename, src_paths=args.src)
  File "/usr/local/lib/python2.7/site-packages/knowledge_repo/post.py", line 347, in from_file
    kp = KnowledgePostConverter.for_file(cls(), filename, format=format, postprocessors=postprocessors).from_file(filename, **opts)
  File "/usr/local/lib/python2.7/site-packages/knowledge_repo/converter.py", line 77, in for_file
    return cls.for_format(kp, get_format(filename, format), postprocessors=postprocessors)
  File "/usr/local/lib/python2.7/site-packages/knowledge_repo/converter.py", line 84, in for_format
    return cls._get_subclass_for(format.lower())(kp, format=format, postprocessors=postprocessors)
  File "/usr/local/lib/python2.7/site-packages/knowledge_repo/converter.py", line 24, in __init__
    check_dependencies(self.dependencies, "Whoops! You are missing some dependencies required to use `{}` instances.".format(self.__class__.__name__))
  File "/usr/local/lib/python2.7/site-packages/knowledge_repo/utils/dependencies.py", line 17, in check_dependencies
    raise RuntimeError('\n\n'.join([message, fix]))
RuntimeError: Whoops! You are missing some dependencies required to use `IpynbFormat` instances.

You can fix this by running:

	pip install --upgrade nbformat nbconvert traitlets

Note: Depending on your system's installation of Python, you may need to use `pip2` or `pip3` instead of `pip`.
```

**Comment by earthmancash** [comment]
hey @philipobrien ! Thanks for filing the issue. So we purposely left out ipynb dependencies in the main install, as some users are not using iPython notebooks as their post contribution medium. To install ipynb in addition to knowledge-repo, you can do `pip install --upgrade knowledge-repo[all]`, which will additionally include dependencies for development tests and PDF uploading.

To make this a bit more clear, I added a line to the quickstart documentation. https://github.com/airbnb/knowledge-repo/commit/2b7d435421aa29fc78cdc83f2504daaaf487b9b9 Hope this helps!

**Comment by philipobrien** [comment]
Ah OK, I should have guessed that. Thanks for the quick reply!
