### ISSUE TITLE
NameError in post preview

### ISSUE THREAD

**Issue by dsimmie** [airbnb/knowledge-repo#217]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

I am hitting a problem when running the quick start. Specifically on the preview command:

`knowledge_repo --repo ./example_repo preview project/example_ipynb`

**Issue**:

* Running preview fails with the following error: `NameError: name 'raw' is not defined`

**Location**:

The offending line is in `app/routes/posts.py`

Line 128: `raw_post = render_post_raw(post) if raw else None`

The variable `raw` does not exist in the function `_render_preview(path, tmpl):`

**System Details**
* KR Version: 0.7.5
* OS: Centos 7

**Full Trace**:

```
Traceback (most recent call last):
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/knowledge_repo/app/models.py", line 137, in __call__
    return self._route(*args, **kwargs)
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/knowledge_repo/app/routes/posts.py", line 39, in render
    return _render_preview(path=path, tmpl=tmpl)
  File "/home/centos/anaconda2/envs/science3/lib/python3.5/site-packages/knowledge_repo/app/routes/posts.py", line 128, in _render_preview
    raw_post = render_post_raw(post) if raw else None
NameError: name 'raw' is not defined
```

**Comment by NiharikaRay** [comment]
Good catch! Here is the corresponding PR: https://github.com/airbnb/knowledge-repo/pull/219
