### ISSUE TITLE
Unable to run quick-start

### ISSUE THREAD

**Issue by aimran** [airbnb/knowledge-repo#286]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Super excited to see this project. However, I am running into some issues getting it to run locally. I installed inside a virtualenv (with pip install knowledge-repo[all])

```
>>knowledge_repo --repo vidya add example_post.ipynb -p project/example_ipynb
INFO:knowledge_repo.repositories.gitrepository:Fetching updates to the knowledge repository...
INFO:knowledge_repo.repositories.gitrepository:Checking out (and/or creating) a new branch `project/example_ipynb.kp`...
INFO:knowledge_repo.repositories.gitrepository:Adding and committing 'project/example_ipynb.kp' to local branch `project/example_ipynb.kp`...
Please enter a commit message for this post: stuff
```

I see that it has successfully created a blob in the `vidya` folder

```bash
├── README.md
└── project
    └── example_ipynb.kp
        ├── REVISION
        ├── UUID
        ├── images
        │   └── output_5_1.png
        ├── knowledge.md
        └── orig_src
            └── example_post.ipynb
```

However, when I run `preview`, it seems to get into a funky state

```
>>knowledge_repo --repo vidya preview project/example_ipynb
INFO:knowledge_repo.repositories.gitrepository:Fetching updates to the knowledge repository...
Traceback (most recent call last):
  File "/Users/asifimran/Code/python/vidya/venv/bin/knowledge_repo", line 278, in <module>
    repo.set_active_draft(kp_path)  # TODO: Deprecate
  File "/Users/asifimran/Code/python/vidya/venv/lib/python2.7/site-packages/knowledge_repo/repositories/gitrepository.py", line 157, in set_active_draft
    branch = self.git_branch_for_post(self._kp_path(path))
  File "/Users/asifimran/Code/python/vidya/venv/lib/python2.7/site-packages/knowledge_repo/repositories/gitrepository.py", line 231, in git_branch_for_post
    if path in self.git_local_posts(branches=[branch]):
  File "/Users/asifimran/Code/python/vidya/venv/lib/python2.7/site-packages/knowledge_repo/repositories/gitrepository.py", line 213, in git_local_posts
    posts[branch] = set([self.__get_path_from_ref(diff.a_path) for diff in self.git_diff(branch)])
  File "/Users/asifimran/Code/python/vidya/venv/lib/python2.7/site-packages/knowledge_repo/repositories/gitrepository.py", line 305, in git_diff
    commit = self.git.commit(ref)
  File "/Users/asifimran/Code/python/vidya/venv/lib/python2.7/site-packages/git/repo/base.py", line 436, in commit
    return self.rev_parse(text_type(rev) + "^0")
  File "/Users/asifimran/Code/python/vidya/venv/lib/python2.7/site-packages/git/repo/fun.py", line 193, in rev_parse
    obj = name_to_object(repo, rev[:start])
  File "/Users/asifimran/Code/python/vidya/venv/lib/python2.7/site-packages/git/repo/fun.py", line 127, in name_to_object
    raise BadName(name)
gitdb.exc.BadName: Ref 'project/example_ipynb.kp' did not resolve to an object
```

**Comment by aimran** [comment]
operator error .. was not obvious that the command should explicitly set the `--knowledge-branch` because drafts are getting stored with same name as the `project` variable

The other option is to merge the branch (same as ```project.kp```) it into master right away.


So, if you still have drafts that is yet to be merged into master

```
>>knowledge_repo --knowledge-branch project/example_ipynb.kp --repo /Users/asifimran/Code/python/vidya preview project/example_ipynb
```
