### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ethen8181** [airbnb/knowledge-repo#349]
Hi team,

Thanks for taking the time to create this! I've been trying to adapt some analysis to Knowledge Repo (KR) and found some missing features/issues to it:

1. Is it possible to change the font size of the text by clicking at some buttons inside a post?
2. The aesthetic for the code chunk and its output looks pretty similar, can this be modified? (In juyter notebook code chunk has a grey background, whereas the output has a white background, but for KR both are in grey)
3. Is it possible to have a table of content floating on the left of a post?
4. Is it having trouble rendering latex (the following latex renders fine in a jupter notebook or nbviewer but fails when using KR)?

<img width="964" alt="latex" src="https://user-images.githubusercontent.com/12273134/32507848-34d5cf0c-c3ae-11e7-814c-aaf73fa0317c.png">

I can submit a separate request if that makes life easier.

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by aaronbiller** [comment]
@ethen8181 Number 3 (table of contents) has actually been implemented since the last release.  If you install from source (in a requirements.txt, `-e git://github.com/airbnb/knowledge-repo.git#egg=knowledge-repo`), you'll get all the updated templates, auth, etc that have been committed to master since 0.7.6.

I agree about the code vs. output aesthetic.  Can you make a PR to adjust that? Should likely be handled [here](https://github.com/airbnb/knowledge-repo/blob/master/knowledge_repo/app/static/css/pages/markdown-base.css#L165-L177).

**Comment by ethen8181** [comment]
@aaronbiller , sorry for the late response. I have zero knowledge about html/css..., do you mean changing it to:

```css
.renderedMarkdown .code-output {
  background: #ffffff;  /* change it to all white */
  padding: 15px;
  overflow: auto;
  border-left: solid #6BD2CA 10px;
}
```

I am having trouble testing this, as I got some errors when executing the latest version (0.7.6) of the knowledge repo. Errors are shown below:

```bash
# borrowing command from the README to create an example post
$ knowledge_repo --repo ./example_repo create ipynb example_post.ipynb

Traceback (most recent call last):
  File "/Users/ethen/anaconda/bin/knowledge_repo", line 4, in <module>
    __import__('pkg_resources').run_script('knowledge-repo==0.7.6', 'knowledge_repo')
  File "/Users/ethen/anaconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/ethen/anaconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1518, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/knowledge_repo' not found in metadata at '/Users/ethen/anaconda/lib/python3.5/site-packages/knowledge_repo-0.7.6.dist-info'
```

Not sure if you've came across the same issue.
