### ISSUE TITLE
Probably just a path issue

### ISSUE THREAD

**Issue by alexhallam** [airbnb/knowledge-repo#359]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Thanks for this great tool. I went to set it up today and had the following error when running 

`knowledge_repo --repo ./example_repo add example_post.Rmd -p project/example_rmd`

Error:

```
'R' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:/Users/AHallam/AppData/Local/Programs/Python/Python37/Scripts/knowledge_repo", line 255, in <module>
    kp = knowledge_repo.KnowledgePost.from_file(args.filename, src_paths=args.src)
  File "C:\users\ahallam\appdata\local\programs\python\python37\lib\site-packages\knowledge_repo\post.py", line 350, in from_file
    kp = KnowledgePostConverter.for_file(cls(), filename, format=format, postprocessors=postprocessors).from_file(filename, **opts)
  File "C:\users\ahallam\appdata\local\programs\python\python37\lib\site-packages\knowledge_repo\converter.py", line 43, in wrapped
    f(*args, **kwargs)
  File "C:\users\ahallam\appdata\local\programs\python\python37\lib\site-packages\knowledge_repo\converters\rmd.py", line 30, in from_file
    subprocess.check_output(runcmd, shell=True)
  File "C:\users\ahallam\appdata\local\programs\python\python37\lib\subprocess.py", line 335, in check_output
    **kwargs).stdout
  File "C:\users\ahallam\appdata\local\programs\python\python37\lib\subprocess.py", line 417, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'R --vanilla --slave -e "library(knitr); setwd('C:\\Users\\AHallam\\data');                         x = knit('C:\\Users\\AHallam\\data\\example_post.Rmd', 'C:\\Users\\AHallam\\AppData\\Local\\Temp\\tmpmjj_8o2y', quiet=T)" ' returned non-zero exit status 1.
```

I am guessing this is just an  `R` path issue. If I am pointed in the right direction, via a link or reference on this error that would be sufficient.

**Comment by danfrankj** [comment]
Hi @alexhallam and thanks for your interest in the knowledge repo. 

This seems like the same problem as in  https://github.com/airbnb/knowledge-repo/issues/46 so let's bring the conversation over there. There's more in depth explanation of the problem and some potential solutions linked in that issue. Please comment there if you're still not able to get around this!
