### ISSUE TITLE
Unable to initialize knowledge repo 

### ISSUE THREAD

**Issue by stephperk** [airbnb/knowledge-repo#394]
Hello,

I am attempting to spin up knowledge repo locally. So far, I have:
* Created and activated virtual environment
* `pip install --upgrade "knowledge-repo[all]"`

Yet, when I follow the next command:

`knowledge_repo --repo C:\Users\sperkins\Projects\repo init`

I get the error:

Traceback (most recent call last):
  File "C:\Users\sperkins\Projects\repo\repo-env\Scripts\knowledge_repo", line 96, in <module>
    repo = knowledge_repo.KnowledgeRepository.for_uri(args.repo)
  File "c:\users\sperkins\projects\repo\repo-env\lib\site-packages\knowledge_repo\repository.py", line 46, in for_uri
    return cls._get_subclass_for(scheme)(uri, *args, **kwargs)
  File "c:\users\sperkins\projects\repo\repo-env\lib\site-packages\knowledge_repo\utils\registry.py", line 24, in _get_subclass_for
    return cls._registry[key]
KeyError: 'c'

Am I missing something?

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by shashj199** [comment]
@stephperk @danias7 For the new version of Knowledge repo, you don't have to create a folder to initialize it to be knowledge repo, the folder will be automatically created. I hope this answers your question, I am not sure if this is the exact error you are looking for. If I create a folder and try to initialize it then I get the following error:

```
Traceback (most recent call last):
  File "/Users/shashank/Envs/knowledgerepo_point8/bin/knowledge_repo", line 96, in <module>
    repo = knowledge_repo.KnowledgeRepository.for_uri(args.repo)
  File "/Users/shashank/Envs/knowledgerepo_point8/lib/python2.7/site-packages/knowledge_repo/repository.py", line 46, in for_uri
    return cls._get_subclass_for(scheme)(uri, *args, **kwargs)
  File "/Users/shashank/Envs/knowledgerepo_point8/lib/python2.7/site-packages/knowledge_repo/repository.py", line 76, in __init__
    self.init(**kwargs)
  File "/Users/shashank/Envs/knowledgerepo_point8/lib/python2.7/site-packages/knowledge_repo/repositories/gitrepository.py", line 67, in init
    self.path = self.uri.replace('git://', '')
  File "/Users/shashank/Envs/knowledgerepo_point8/lib/python2.7/site-packages/knowledge_repo/repositories/gitrepository.py", line 106, in path
    path), "Provided path '{}' is not a valid repository.".format(path)
AssertionError: Provided path '/Users/shashank/CheckKRAgainpoint8' is not a valid repository.
```
If I don't create a folder then it initializes successfully

**Comment by brunamnc** [comment]
@stephperk try using a relative path instead of an absolute path, such as: 

knowledge_repo --repo .\test init

I was having the same issue as you but this worked for me. Hope this helps!

**Comment by sayakpaul** [comment]
I was also having the same issue. I followed @brunamnc's suggestion and it worked. Thanks!

**Comment by brunoritter** [comment]
I'm having the same `KeyError: 'c'` for every operation that needs the `<repo_path>` argument. I've managed to create the repository using @brunamnc workaround, but then I can't create the example posts on the folder or start the server for the webapp. Running on Windows 10.

**Comment by ppeiris** [comment]
**I got this error when I try to launch the server.** 

```
Traceback (most recent call last):
  File "/path/to/my/repo", line 263, in <module>
    raise RuntimeError("Could not initialise knowledge repository for uri `{}`. Please check the uri, and try again.".format(args.repo))
RuntimeError: Could not initialise knowledge repository for uri `/path/to/my/repo`. Please check the uri, and try again.
```
### Solution:

The issue was I was not initializing the repo correctly. 

this is how I initialize the repo (**and this is the wrong way to do it**)

```
knowledge_repo --repo /path/to/my/repo runserver
```
Even this is wrong, it did not give me any errors and created the dir with `.knowledge_repo_config.yml` file, so I thought it was created properly 

The CORRECT way to initialize it

```
knowledge_repo --repo git:///path/to/my/repo runserver
```

Please not the `git://` and then the path to the location on your machine. 

After creating the repo this way, I was able to run the server.
