### ISSUE TITLE
No module named MySQLdb

### ISSUE THREAD

**Issue by phesami** [airbnb/knowledge-repo#444]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj 

I'm on Python 2.7 and seeing the following issue when trying to point the knowlege_repo script to my local db:

`knowledge_repo --repo mysql://user:pass@localhost/knowledge_repo_db:knowlege_repo_table`
```
Traceback (most recent call last):
  File "/Users/phesami/anaconda/bin/knowledge_repo", line 96, in <module>
    repo = knowledge_repo.KnowledgeRepository.for_uri(args.repo)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/knowledge_repo/repository.py", line 46, in for_uri
    return cls._get_subclass_for(scheme)(uri, *args, **kwargs)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/knowledge_repo/repository.py", line 76, in __init__
    self.init(**kwargs)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/knowledge_repo/repositories/dbrepository.py", line 49, in init
    self.engine = create_engine(engine_uri, pool_recycle=3600)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 110, in dbapi
    return __import__('MySQLdb')
ImportError: No module named MySQLdb
```

Any advice how to resolve this?  Any way to change the SQLALCHEMY_DATABASE_URI?

**Comment by phesami** [comment]
Thanks. The `--dburi` option solved MySQLdb import issue, however now I'm seeing the following:
```
INFO:knowledge_repo.repositories.gitrepository:Fetching updates to the knowledge repository...
INFO:alembic.runtime.migration:Context impl MySQLImpl.
INFO:alembic.runtime.migration:Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/Users/phesami/anaconda/bin/knowledge_repo", line 320, in <module>
    use_reloader=args.debug and args.action == 'runserver'
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/knowledge_repo/app/deploy/flask.py", line 9, in run
    app = self.app
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/knowledge_repo/app/deploy/common.py", line 61, in app
    return self.builder_func()
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/knowledge_repo/app/deploy/common.py", line 14, in get_app
    return knowledge_repo.KnowledgeRepository.for_uri(uris).get_app(db_uri=db_uri, debug=debug, config=config, **kwargs)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/knowledge_repo/repository.py", line 400, in get_app
    return self.config.prepare_app(app.KnowledgeFlask(self, *args, **kwargs))
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/knowledge_repo/app/app.py", line 91, in __init__
    self.db_init()
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/knowledge_repo/app/app.py", line 288, in db_init
    sqlalchemy_db.create_all()
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 4005, in create_all
    tables=tables)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/phesami/anaconda/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function VARCHAR(100), \n\tlocation VARCHAR(255), \n\tmessage TEXT, \n\ttraceback TEXT' at line 3") [SQL: u'\nCREATE TABLE errorlog (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tfunction VARCHAR(100), \n\tlocation VARCHAR(255), \n\tmessage TEXT, \n\ttraceback TEXT, \n\tversion VARCHAR(100), \n\tcreated_at DATETIME, \n\tPRIMARY KEY (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by phesami** [comment]
actually I was able to overcome this by switching to postgres :) Thanks for the help!
