### ISSUE TITLE
Not able to run add any file to a repo which I have created 

### ISSUE THREAD

**Issue by vatsaluc** [airbnb/knowledge-repo#500]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj
Hi,
I have installed knowledge_repo 0.8.8 on a remote server, on python2.7.
I am able to do knowledge_repo --version
I have created a test file using the following command:
knowledge_repo --repo <path>  create ipynb test2.ipynb

When I add this file so that it could be displayed on the web editor using following command:-
knowledge_repo --repo <path> add --branch master test1.ipynb

I am getting the following error:-

Traceback (most recent call last):
  File "/usr/local/bin/knowledge_repo", line 288, in <module>
    kp = knowledge_repo.KnowledgePost.from_file(args.filename, src_paths=args.src)
  File "/usr/local/lib/python2.7/dist-packages/knowledge_repo/post.py", line 489, in from_file
    kp = KnowledgePostConverter.for_file(cls(), filename, format=format, postprocessors=postprocessors, interactive=interactive).from_file(filename, **opts)
  File "/usr/local/lib/python2.7/dist-packages/knowledge_repo/converter.py", line 52, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/knowledge_repo/converters/ipynb.py", line 53, in from_file
    from nbconvert import MarkdownExporter
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/__init__.py", line 7, in <module>
    from . import postprocessors
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
    from .serve import ServePostProcessor
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/postprocessors/serve.py", line 12, in <module>
    from tornado import web, ioloop, httpserver, log, gen
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 205
    application: "Application",
               ^
SyntaxError: invalid syntax

Is this due to some version issue or I have done the installation incorrectly?

**Comment by bulam** [comment]
Hi @vatsaluc I believe the issue is that in your command, you are not specifying the path to your knowledge repo after the `--repo` part.

The command should be in this format:
`knowledge_repo --repo <path/uri_of_repo> create Rmd example_post.Rmd`

If you are currently in the repo, then you would need to specify the path with a dot like `knowledge_repo --repo . add`

Feel free to reopen this issue if you're still having trouble!
