### ISSUE TITLE
Just wanted to test with sqlite

### ISSUE THREAD

**Issue by patchie** [airbnb/knowledge-repo#504]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hi, Just wanted to test with sqlite, and tried to follow this tutorial: https://knowledge-repo.readthedocs.io/en/latest/deployment.html

got stuck when i tried: **knowledge_repo --repo sqlite://sqlite.db init**
I got the error message: **sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'sqlite'**

Hope you can help, thanks in advance.

Full error message below:
```
C:\knowledge_repo_test>knowledge_repo --repo sqlite://sqlite.db init
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\knowledge_repo", line 96, in <module>
    repo = knowledge_repo.KnowledgeRepository.for_uri(args.repo)
  File "c:\program files (x86)\python37-32\lib\site-packages\knowledge_repo\repository.py", line 47, in for_uri
    return cls._get_subclass_for(scheme).from_uri(uri, *args, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\knowledge_repo\repository.py", line 63, in from_uri
    return cls(url, *args, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\knowledge_repo\repository.py", line 81, in __init__
    self.init(**kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\knowledge_repo\repositories\dbrepository.py", line 49, in init
    self.engine = create_engine(engine_uri, pool_recycle=3600)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\engine\__init__.py", line 424, in create_engine
    return strategy.create(*args, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\engine\strategies.py", line 50, in create
    u = url.make_url(name_or_url)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\engine\url.py", line 211, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\engine\url.py", line 270, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name)
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'sqlite'

C:\knowledge_repo_test>
```

**Comment by tkocmathla** [comment]
Based on the [SQLite docs](https://www.sqlite.org/uri.html), I think you want to use:
```
$ knowledge_repo --repo file://sqlite.db init
Knowledge repository successfully initialized for uri `/tmp/sqlite.db`.
```

**Comment by patchie** [comment]
Thanks @tkocmathla.

Just to update. It actually creates a folder, and doesn't seem to use SQLITE.
But it works anyway.

`knowledge_repo --repo file://knowledge_repo init`
This command will create a folder called "knowledge_repo"

**Comment by naoyak** [comment]
Remember you need [extra slashes in the URI](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlite) depending on the type of SQLite database (in-memory, file, etc).
