### ISSUE TITLE
Database connection errors with git-based repository

### ISSUE THREAD

**Issue by tkocmathla** [airbnb/knowledge-repo#507]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

I have a problem that on the surface looks like #430, but I am using a git-based knowledge repo with a MySQL database for the web app backend. When running under deploy, I get nasty internal server errors related to the database on the first few page loads, and intermittently afterwards (after each reindexing run?). If I use runserver, the app serves pages without error.

The deploy errors look like this:
```
[2019-03-25 18:07:17 +0000] [23916] [ERROR] Error handling request /feed
...stack trace elided...
mysql.connector.errors.OperationalError: MySQL Connection not available.

The above exception was the direct cause of the following exception:
...stack trace elided...
sqlalchemy.exc.OperationalError: (mysql.connector.errors.OperationalError) MySQL Connection not available.
[SQL: SELECT tags.description AS tags_description, tags.id AS tags_id, tags.name AS tags_name, tags.created_at AS tags_created_at
FROM tags
WHERE tags.name = %(name_1)s
 LIMIT %(param_1)s]
[parameters: [{}]]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

I've tried using both `mysql` and `mysql+mysqlconnector` drivers but the problem exists for both.

**Comment by vatsaluc** [comment]
**I am facing the same issue can someone help me.**

Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/anaconda/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/anaconda/lib/python3.7/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/opt/anaconda/lib/python3.7/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/anaconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda/lib/python3.7/site-packages/knowledge_repo/app/index.py", line 46, in index_sync_loop
    update_index(check_timeouts=False)
  File "/opt/anaconda/lib/python3.7/site-packages/knowledge_repo/app/models.py", line 140, in wrapped
    raise_with_traceback(e)
  File "/opt/anaconda/lib/python3.7/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/opt/anaconda/lib/python3.7/site-packages/knowledge_repo/app/models.py", line 135, in wrapped
    return function(*args, **kwargs)
  File "/opt/anaconda/lib/python3.7/site-packages/knowledge_repo/app/index.py", line 147, in update_index
    if not is_index_master and not force or index_up_to_date():
  File "/opt/anaconda/lib/python3.7/site-packages/knowledge_repo/app/index.py", line 121, in index_up_to_date
    for uri, revision in current_repo.revisions.items():
  File "/opt/anaconda/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/anaconda/lib/python3.7/site-packages/knowledge_repo/repository.py", line 132, in revisions
    return {self.uri: self.revision}
  File "/opt/anaconda/lib/python3.7/site-packages/knowledge_repo/repositories/dbrepository.py", line 68, in revision
    return str(self.session.query(func.max(self.PostRef.updated_at)).first()[0])
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3215, in first
    ret = list(self[0:1])
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3007, in __getitem__
    return list(res)
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/anaconda/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/anaconda/lib/python3.7/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/opt/anaconda/lib/python3.7/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: SELECT max(test.updated_at) AS max_1 
FROM test 
 LIMIT %s]
[parameters: (1,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by Mehdi-Bendriss** [comment]
@tkocmathla @vatsaluc did you manage to find a workaround for this?

**Comment by nmcalabroso** [comment]
Also facing this issue. I've tried replacing postgres with mysql and still the same problem exists. I think this has something to do with how the flask application is handling multiple threads. I will try the solutions posted in https://github.com/airbnb/knowledge-repo/issues/430 and will update this issue.

**Comment by gthomas-slack** [comment]
I am facing similar issues. I put together a docker image to reproduce the issue here: https://github.com/airbnb/knowledge-repo/issues/430#issuecomment-506918693
