### ISSUE TITLE
knowledge_repo add fails: missing template

### ISSUE THREAD

**Issue by glemarivero** [airbnb/knowledge-repo#578]
Python 3.7
Steps to reproduce:
`pip install --upgrade "knowledge-repo[all]"`
`knowledge_repo --version`
Local version: 0.8.9
`knowledge_repo --repo ./test_repo init`
`knowledge_repo --repo ./test_repo create ipynb example.ipynb`
`knowledge_repo --repo ./test_repo add example.ipynb -p project/example_ipynb`

```
INFO:knowledge_repo.repositories.gitrepository:Fetching updates to the knowledge repository...
Traceback (most recent call last):
  File "/home/tglema/.envs/wrinkles_cnn/bin/knowledge_repo", line 288, in <module>
    kp = knowledge_repo.KnowledgePost.from_file(args.filename, src_paths=args.src)
  File "/home/tglema/.envs/wrinkles_cnn/lib/python3.6/site-packages/knowledge_repo/post.py", line 489, in from_file
    kp = KnowledgePostConverter.for_file(cls(), filename, format=format, postprocessors=postprocessors, interactive=interactive).from_file(filename, **opts)
  File "/home/tglema/.envs/wrinkles_cnn/lib/python3.6/site-packages/knowledge_repo/converter.py", line 52, in wrapped
    f(*args, **kwargs)
  File "/home/tglema/.envs/wrinkles_cnn/lib/python3.6/site-packages/knowledge_repo/converters/ipynb.py", line 69, in from_file
    (body, resources) = md_exporter.from_notebook_node(nb)
  File "/home/tglema/.envs/wrinkles_cnn/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 384, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/home/tglema/.envs/wrinkles_cnn/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/tglema/.envs/wrinkles_cnn/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/tglema/.envs/wrinkles_cnn/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
jinja2.exceptions.TemplateNotFound: markdown.tpl
```

I've copied a mardown.tpl file to my `~/envs/repo3/lib/python3.7/site-packages/nbconvert/templates/` folder, but I get the same error.

Thanks

**Comment by npelikan** [comment]
Hi @glemarivero -- From my testing, it appears that you can solve the issue above using:

```bash
pip install --upgrade nbformat 'nbconvert<6.0.0[execute]' traitlets
```
And try again.

I've submitted a PR to pin to the correct version of nbconvert.
