### ISSUE TITLE
markdown.tpl template not found error thrown by jinja2

### ISSUE THREAD

**Issue by iandesj** [airbnb/knowledge-repo#590]
When I execute `knowledge_repo  add example_post.ipynb -p project/example_ipynb` I am getting this exception.
I get this whether I explicitly provide the repo path or if it's in an environmental variable. Tried on both Linux and Mac OS.

```bash
Traceback (most recent call last):
  File "/Users/idesjardins/Workspace/scratch/knowledge_repo/venv/bin/knowledge_repo", line 288, in <module>
    kp = knowledge_repo.KnowledgePost.from_file(args.filename, src_paths=args.src)
  File "/Users/idesjardins/Workspace/scratch/knowledge_repo/venv/lib/python3.8/site-packages/knowledge_repo/post.py", line 489, in from_file
    kp = KnowledgePostConverter.for_file(cls(), filename, format=format, postprocessors=postprocessors, interactive=interactive).from_file(filename, **opts)
  File "/Users/idesjardins/Workspace/scratch/knowledge_repo/venv/lib/python3.8/site-packages/knowledge_repo/converter.py", line 52, in wrapped
    f(*args, **kwargs)
  File "/Users/idesjardins/Workspace/scratch/knowledge_repo/venv/lib/python3.8/site-packages/knowledge_repo/converters/ipynb.py", line 69, in from_file
    (body, resources) = md_exporter.from_notebook_node(nb)
  File "/Users/idesjardins/Workspace/scratch/knowledge_repo/venv/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 384, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/Users/idesjardins/Workspace/scratch/knowledge_repo/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/idesjardins/Workspace/scratch/knowledge_repo/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/idesjardins/Workspace/scratch/knowledge_repo/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
jinja2.exceptions.TemplateNotFound: markdown.tpl
```

**Comment by JoshNettletonGit** [comment]
Hey Ian, have you made any progress with this? I've been stuck with the same issue for a couple of days and have not found a solution yet

**Comment by iandesj** [comment]
> Hey Ian, have you made any progress with this? I've been stuck with the same issue for a couple of days and have not found a solution yet

I have yet to get over this hump!

**Comment by GuySerfaty** [comment]
same here...

**Comment by bulam** [comment]
Hi all, sorry about the delay. In the latest 0.9.0 release, the version of nbconvert and nbformat is pinned to below 6.0, which should resolve this issue. Please comment if you still run into problems with this.
