### ISSUE TITLE
running web app gets stuck in alembic migration

### ISSUE THREAD

**Issue by ametersky** [airbnb/knowledge-repo#72]
running `knowledge_repo --repo datasci_knowledge/ runserver` gives the following output.

I've been stuck on the last log for about ~10 mins.  I figure it shouldn't take this long because it's either an empty migration or it is initializing the db?

```
INFO:knowledge_repo.repositories.gitrepository:Fetching updates to the knowledge repository...
INFO:alembic.runtime.migration:Context impl SQLiteImpl.
INFO:alembic.runtime.migration:Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> 1b385158fd32
```

This is the page I am presented with at `localhost:7000`

![image](https://cloud.githubusercontent.com/assets/13753810/19322314/89c426a0-9086-11e6-8056-56b6e8ad39bf.png)

**Comment by NiharikaRay** [comment]
Could you add the `--debug` flag to the command? That'll give some more information. 

`knowledge_repo --repo datasci_knowledge/ runserver --debug`

**Comment by ametersky** [comment]
Adding the `--debug` flag doesn't give any extra output, unfortunately.

**Comment by ametersky** [comment]
I just looked in `/tmp` to see if the database was ever created and I'm not seeing anything there.

**Comment by ametersky** [comment]
Also, just realized this would show debug info in the web app, not the logs.  Here is the debug info from the web app :facepalm:

```
TypeError
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last)
File "/Users/andrewmetersky/.virtualenvs/knowledge_repo/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/andrewmetersky/.virtualenvs/knowledge_repo/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/Users/andrewmetersky/.virtualenvs/knowledge_repo/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/andrewmetersky/.virtualenvs/knowledge_repo/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/Users/andrewmetersky/.virtualenvs/knowledge_repo/lib/python2.7/site-packages/flask/app.py", line 1634, in full_dispatch_request
self.try_trigger_before_first_request_functions()
File "/Users/andrewmetersky/.virtualenvs/knowledge_repo/lib/python2.7/site-packages/flask/app.py", line 1660, in try_trigger_before_first_request_functions
func()
File "/Users/andrewmetersky/.virtualenvs/knowledge_repo/lib/python2.7/site-packages/knowledge_repo/app/app.py", line 130, in update_index_and_typeahead_data
for tag in excluded_tags:
TypeError: 'NoneType' object is not iterable

```

**Comment by NiharikaRay** [comment]
Hi! PR for this bugfix is out: https://github.com/airbnb/knowledge-repo/pull/73

**Comment by ametersky** [comment]
Thanks for being so speedy!

**Comment by NiharikaRay** [comment]
The bugfix was merged - let us know if you're still running into issues!

**Comment by ametersky** [comment]
Thanks! Going to test it out now.
